version: '3.4'

services:
  api:
    image: demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - APP_URL=jdbc:postgresql://host.docker.internal:5432/demo
      - APP_USERNAME=postgres
      - APP_PASSWORD=paula@123