micronaut:
  application:
    name: demo

datasources:
  default:
    url: ${APP_URL:`jdbc:postgresql://host.docker.internal:5432/demo`}
    username: ${APP_USERNAME:postgres}
    password: ${APP_PASSWORD:paula@123}
    driverClassName: org.postgresql.Driver

---
jpa:
  default:
    packages-to-scan:
      - 'com.itau.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true