micronaut:
  application:
    name: demo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/demo
    driverClassName: org.postgresql.Driver
    username: postgres
    password: paula@123
---
jpa:
  default:
    packages-to-scan:
      - 'com.itau.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true